### ISSUE TITLE
- 00 - Introduction - Jeremy Glover

### ISSUE THREAD

**Issue by Jeremy-Glover** [TIY-LR-FEE-2015-Fall/assignments#2]
<h1>Name: Jeremy Glover</h1>

<h4>Username: Jeremy-Glover</h4>

- I think one of the main difficulties will just be getting _familiar_ and _comfortable_ with all of the syntax and terms used for different programs and software. As someone relatively unfamiliar with coding and programming, trying to make sure I understand everything I am reading and how it applies has taken some time in the prework. In the past if I have trouble understanding and applying something new I usually start again at the beginning and try to understand all of the basics leading up to difficulty. I can get agitated with myself if I don't immediately understand. One thing I try to lean on at times like this is looking back at past experiences where I struggled and remembering how I figured things out and made the most of the experience.
- The prework I enjoyed _most_ was personalizing a website using **CSS** as this gave me some basic feel of what can be done on the creative end of front-end engineering. The prework I liked the _least_ would be learning about **Github** as it is not immediately intuitive and will take practice to get used to how it works and what you can do with it when working on assignments.

**Comment by pixiestix826** [comment]
Hi @Jeremy-Glover, Looking forward to collaborating with you soon. Peace, Brandi
