### ISSUE TITLE
06-css-specificity-chancey ward

### ISSUE THREAD

**Issue by chanceyw** [TIY-LR-FEE-2015-Fall/assignments#31]
1. red
2. yellow
3. black
4. blue
5. red
6. 8 px, 0
7. none
8. #fff
9. red
10. green

**Comment by rtablada** [comment]
@chanceyw make sure to name the issue properly it should be 

`${assignmentNumber} - ${assignmentName} - ${firstName} ${lastName}`

**Comment by rtablada** [comment]
@chanceyw check 5 & 6 and still missing 10

**Comment by chanceyw** [comment]
changed answers ready to review
