### ISSUE TITLE
02-Basic Git PR- Brian Stickney

### ISSUE THREAD

**Issue by BrianStick** [TIY-LR-FEE-2015-Fall/assignments#8]
- [x] Create a new Issue with these tasks!
- [x] Use the `hub` cli to create a repository called `02-basic-git-pr`
- [x] Use the `git` cli to create a branch called `develop`
- [x] In Github, open a PR _from_ `develop` _into_ `master`
- [x] Create your personal website
  - [x] Checkpoint: Created and committed `index.html`
  - [x] Complete: Pushed `index.html`
- [x] Add basic text and background styles
  - [x] Checkpoint: Created and committed `styles.css`
  - [x] Checkpoint: Linked `styles.css` in `index.html` and committed
  - [x] Complete: Pushed changes

**Comment by BrianStick** [comment]
https://github.com/BrianStick/02-basic-git-pr/pull/1

**Comment by rtablada** [comment]
@BrianStick looks like some of the work on your local machine may not be pushed to Github.

Some of the issues with syntax can be helped by relying more on tab completion so that it gives you all the valid markup.
Also checking indentation will make it easier to see mistakes ore nesting.

**Comment by BrianStick** [comment]
@rtablada Been pushed to Github

**Comment by rtablada** [comment]
@BrianStick still missing picture of you and some general styling

**Comment by rtablada** [comment]
@BrianStick :+1:
